name: Release package

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code (Cloning the repository in the virtual machine)
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/action-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Create Release Pull Request or Publish to npm and create a release on GitHub
        id: changesets
        uses: changesets/action@v1
        with:
          version: bun run changeset version
          publish: bun run release
        env:
          # Changesets needs a GitHub token to be able to create a release pull request
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # If you want to publish to npm, you need to set up an npm token, so changesets can publish your packages
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
